import React from "react";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — EcoVerse",
  description: "Learn how EcoVerse collects, uses, and protects your personal data in compliance with the Indian IT Act 2000 and PDPB 2023.",
};

export default function PrivacyPolicyPage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#0a1a0e",
        color: "#E8F5E9",
        fontFamily: "var(--font-sans), sans-serif",
        padding: "80px 24px 120px",
      }}
    >
      <div style={{ maxWidth: "800px", margin: "0 auto" }}>
        {/* Back link */}
        <Link
          href="/"
          style={{ color: "#66BB6A", textDecoration: "none", fontSize: "0.875rem", fontWeight: 600, display: "inline-flex", alignItems: "center", gap: "6px", marginBottom: "48px" }}
        >
          ← Back to EcoVerse
        </Link>

        {/* Header */}
        <div style={{ marginBottom: "56px", borderBottom: "1px solid rgba(102,187,106,0.15)", paddingBottom: "32px" }}>
          <span style={{ fontSize: "0.75rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "#66BB6A" }}>
            Legal
          </span>
          <h1 style={{ fontSize: "clamp(2rem, 4vw, 3rem)", fontWeight: 800, marginTop: "12px", letterSpacing: "-0.025em" }}>
            Privacy Policy
          </h1>
          <p style={{ color: "rgba(232,245,233,0.55)", marginTop: "12px", lineHeight: 1.7 }}>
            Last updated: June 2026 &nbsp;|&nbsp; Effective for ecoverseindia.web.app
          </p>
          <p style={{ color: "rgba(232,245,233,0.7)", marginTop: "16px", lineHeight: 1.8 }}>
            EcoVerse (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, share, and safeguard your information when you use our platform. It is governed by the Indian Information Technology Act, 2000 and the Personal Data Protection Bill (PDPB), 2023.
          </p>
        </div>

        <LegalSection title="1. Information We Collect">
          <LegalParagraph>
            We collect information you provide directly to us, and some information automatically generated by your use of EcoVerse:
          </LegalParagraph>
          <LegalList items={[
            "Name, email address, and phone number (required during signup)",
            "Profile photo (optional, uploaded by user)",
            "City and state (for community and map features)",
            "Role preferences: Rescuer, Volunteer, Adopter, NGO, Vegan/Animal Lover, Feeder/Caretaker",
            "Animal rescue case reports including: animal type, severity, area-level location (rounded to ~1.1km, NOT exact GPS), description, and photos/videos you upload",
            "Optional dietary preference and community interests",
            "Device and browser information (for security and performance)",
            "Activity logs within the platform (reports submitted, rescues accepted, etc.)",
          ]} />
        </LegalSection>

        <LegalSection title="2. How We Use Your Information">
          <LegalList items={[
            "To create and manage your EcoVerse account",
            "To connect volunteers, rescuers, and NGOs for animal welfare coordination",
            "To send rescue alerts and SOS notifications via Firebase Cloud Messaging",
            "To display your public profile information on the community map (only non-PII data: display name, city, roles)",
            "To improve platform performance and fix bugs",
            "To communicate important updates about your rescue cases or account",
            "To prevent fraud, abuse, and protect the safety of our community",
          ]} />
        </LegalSection>

        <LegalSection title="3. Location Data — Area-Level Only">
          <LegalParagraph>
            EcoVerse is designed with privacy-first location handling. When you report an animal rescue case, your GPS coordinates are <strong style={{ color: "#66BB6A" }}>rounded to area-level precision</strong> (approximately ±1.1km) before being stored in our database. Exact GPS coordinates are never stored in rescue case records.
          </LegalParagraph>
          <LegalParagraph>
            On the public map, rescue case markers have an additional random offset of ±300 meters applied so that the exact area cannot be reverse-pinpointed. Only the broad zone is visible.
          </LegalParagraph>
        </LegalSection>

        <LegalSection title="4. Third-Party Services">
          <LegalParagraph>We use the following trusted third-party services to run EcoVerse:</LegalParagraph>
          <LegalList items={[
            "Firebase Authentication (Google) — for secure user login",
            "Cloud Firestore (Google) — for our database",
            "Firebase Cloud Messaging (FCM) — for push notifications",
            "Cloudflare R2 — for storing uploaded photos and videos securely",
            "Leaflet.js + OpenStreetMap/CartoDB — for map rendering (no user data sent to map providers)",
          ]} />
          <LegalParagraph>
            These providers have their own privacy policies. We encourage you to review them. We do not sell your data to any third party, ever.
          </LegalParagraph>
        </LegalSection>

        <LegalSection title="5. Your Rights">
          <LegalParagraph>You have the following rights over your data:</LegalParagraph>
          <LegalList items={[
            "Access: Request a copy of the personal data we hold about you",
            "Correction: Ask us to fix inaccurate or incomplete data",
            "Deletion: Request deletion of your account and all associated personal data",
            "Portability: Request your data in a machine-readable format",
            "Withdraw Consent: Opt out of non-essential notifications at any time",
          ]} />
          <LegalParagraph>
            To exercise any right, email us at <a href="mailto:manish63018@gmail.com" style={{ color: "#66BB6A" }}>manish63018@gmail.com</a>. We will respond within 30 days.
          </LegalParagraph>
        </LegalSection>

        <LegalSection title="6. Data Retention">
          <LegalParagraph>
            We retain your account data for as long as your account is active. Rescue case records are retained for 2 years for safety audit purposes, then anonymized. You may request early deletion at any time.
          </LegalParagraph>
        </LegalSection>

        <LegalSection title="7. Children&apos;s Policy">
          <LegalParagraph>
            EcoVerse is intended for users aged 13 and above. We do not knowingly collect personal data from children under 13. If we discover such data has been collected, we will delete it immediately. Parents/guardians may contact us at <a href="mailto:manish63018@gmail.com" style={{ color: "#66BB6A" }}>manish63018@gmail.com</a>.
          </LegalParagraph>
        </LegalSection>

        <LegalSection title="8. Security">
          <LegalParagraph>
            We use industry-standard security measures including HTTPS encryption, Firestore security rules, and role-based access control. However, no system is 100% secure — we encourage you to use strong passwords and report any suspicious activity.
          </LegalParagraph>
        </LegalSection>

        <LegalSection title="9. Contact">
          <LegalParagraph>
            For any privacy concerns or data requests, contact us at:<br />
            📧 <a href="mailto:manish63018@gmail.com" style={{ color: "#66BB6A" }}>manish63018@gmail.com</a><br />
            This policy is governed by the laws of India (IT Act 2000, PDPB 2023).
          </LegalParagraph>
        </LegalSection>
      </div>
    </div>
  );
}

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: "40px" }}>
      <h2 style={{ fontSize: "1.25rem", fontWeight: 700, color: "#A5D6A7", marginBottom: "16px", letterSpacing: "-0.01em" }}>
        {title}
      </h2>
      {children}
    </div>
  );
}

function LegalParagraph({ children }: { children: React.ReactNode }) {
  return (
    <p style={{ color: "rgba(232,245,233,0.75)", lineHeight: 1.8, marginBottom: "12px", fontSize: "0.95rem" }}>
      {children}
    </p>
  );
}

function LegalList({ items }: { items: string[] }) {
  return (
    <ul style={{ paddingLeft: "20px", margin: "0 0 16px 0", display: "flex", flexDirection: "column", gap: "8px" }}>
      {items.map((item, i) => (
        <li key={i} style={{ color: "rgba(232,245,233,0.7)", lineHeight: 1.7, fontSize: "0.9rem" }}>
          {item}
        </li>
      ))}
    </ul>
  );
}
