export interface City {
  id: string;
  name: string;
  state: string;
}

export const INDIAN_CITIES: City[] = [
  { id: "mumbai", name: "Mumbai", state: "Maharashtra" },
  { id: "delhi", name: "Delhi", state: "Delhi" },
  { id: "bengaluru", name: "Bengaluru", state: "Karnataka" },
  { id: "hyderabad", name: "Hyderabad", state: "Telangana" },
  { id: "ahmedabad", name: "Ahmedabad", state: "Gujarat" },
  { id: "chennai", name: "Chennai", state: "Tamil Nadu" },
  { id: "kolkata", name: "Kolkata", state: "West Bengal" },
  { id: "surat", name: "Surat", state: "Gujarat" },
  { id: "pune", name: "Pune", state: "Maharashtra" },
  { id: "jaipur", name: "Jaipur", state: "Rajasthan" },
  { id: "lucknow", name: "Lucknow", state: "Uttar Pradesh" },
  { id: "kanpur", name: "Kanpur", state: "Uttar Pradesh" },
  { id: "nagpur", name: "Nagpur", state: "Maharashtra" },
  { id: "indore", name: "Indore", state: "Madhya Pradesh" },
  { id: "thane", name: "Thane", state: "Maharashtra" },
  { id: "bhopal", name: "Bhopal", state: "Madhya Pradesh" },
  { id: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh" },
  { id: "patna", name: "Patna", state: "Bihar" },
  { id: "vadodara", name: "Vadodara", state: "Gujarat" },
  { id: "ghaziabad", name: "Ghaziabad", state: "Uttar Pradesh" },
  { id: "ludhiana", name: "Ludhiana", state: "Punjab" },
  { id: "agra", name: "Agra", state: "Uttar Pradesh" },
  { id: "nashik", name: "Nashik", state: "Maharashtra" },
  { id: "faridabad", name: "Faridabad", state: "Haryana" },
  { id: "meerut", name: "Meerut", state: "Uttar Pradesh" },
  { id: "rajkot", name: "Rajkot", state: "Gujarat" },
  { id: "varanasi", name: "Varanasi", state: "Uttar Pradesh" },
  { id: "srinagar", name: "Srinagar", state: "Jammu and Kashmir" },
  { id: "aurangabad", name: "Aurangabad", state: "Maharashtra" },
  { id: "dhanbad", name: "Dhanbad", state: "Jharkhand" },
  { id: "amritsar", name: "Amritsar", state: "Punjab" },
  { id: "navi-mumbai", name: "Navi Mumbai", state: "Maharashtra" },
  { id: "allahabad", name: "Allahabad", state: "Uttar Pradesh" },
  { id: "ranchi", name: "Ranchi", state: "Jharkhand" },
  { id: "howrah", name: "Howrah", state: "West Bengal" },
  { id: "coimbatore", name: "Coimbatore", state: "Tamil Nadu" },
  { id: "jabalpur", name: "Jabalpur", state: "Madhya Pradesh" },
  { id: "gwalior", name: "Gwalior", state: "Madhya Pradesh" },
  { id: "vijayawada", name: "Vijayawada", state: "Andhra Pradesh" },
  { id: "jodhpur", name: "Jodhpur", state: "Rajasthan" },
  { id: "madurai", name: "Madurai", state: "Tamil Nadu" },
  { id: "raipur", name: "Raipur", state: "Chhattisgarh" },
  { id: "kota", name: "Kota", state: "Rajasthan" },
  { id: "guwahati", name: "Guwahati", state: "Assam" },
  { id: "chandigarh", name: "Chandigarh", state: "Punjab/Haryana" },
  { id: "dehradun", name: "Dehradun", state: "Uttarakhand" },
  { id: "kochi", name: "Kochi", state: "Kerala" },
  { id: "bhubaneswar", name: "Bhubaneswar", state: "Odisha" }
];
